services:
  ruoyi-server:
    image: ruoyi/ruoyi-server:5.3.1
    container_name: ruoyi-server
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8080
    volumes:
      # 配置文件
      - /docker/server1/logs/:/ruoyi/server/logs/
      # skywalking 探针
#      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    privileged: true
    network_mode: "host"

  ruoyi-monitor-admin:
    image: ruoyi/ruoyi-monitor-admin:5.3.1
    container_name: ruoyi-monitor-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/monitor/logs/:/ruoyi/monitor/logs
    privileged: true
    network_mode: "host"

  ruoyi-snailjob-server:
    image: ruoyi/ruoyi-snailjob-server:5.3.1
    container_name: ruoyi-snailjob-server
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "8800:8800"
      - "17888:17888"
    volumes:
      - /docker/snailjob/logs/:/ruoyi/snailjob/logs
    privileged: true
    network_mode: "host"
